Feat: deploy from travis
prostofrost/adidas-shop-react pull request #14
Opened 2017-05-31 10:36 UTC by prostofrost

Настроен скрипт деплоя.
Настроен алиас на https://demo-adidas-prostofrost.now.sh

p.s.: деплой настроен с ветки feat/deploy-from-travis для тестов, после мерджа перенастрою на master

2017-05-31 11:06 UTC, imevro requested changes

2017-05-31 11:06 UTC, evgenyrodionov commented on package.json
> +    "alias": [
поч массив?

2017-05-31 11:06 UTC, evgenyrodionov commented on deploy.sh
>  #!/usr/bin/env bash
А зачем отдельный файл, а не в тревисе?

2017-05-31 11:06 UTC, evgenyrodionov commented on deploy.sh
>  #!/usr/bin/env bash
Обсуждаемо

2017-05-31 11:20 UTC, prostofrost commented on deploy.sh
>  #!/usr/bin/env bash
Потому что он выдает ошибку 127. Описания ошибок и их решений в документаций не нашел.
Люди решают проблему просто, добавлением sh перед путем к файлу с деплоем.
https://github.com/containous/traefik/pull/1103

Почему это работает, не могу сказать, как и не могу сказать почему выдает ошибку 127

2017-05-31 22:27 UTC, evgenyrodionov commented on deploy.sh
>  #!/usr/bin/env bash
А переделай на нпм скрипт

2017-06-01 09:25 UTC, prostofrost commented on deploy.sh
>  #!/usr/bin/env bash
Переделал. deploy.sh удалил

2017-06-01 12:20 UTC, merged