adidas-shop init
prostofrost/adidas-shop-react pull request #2
Opened 2017-05-10 12:51 UTC by prostofrost

Первая итерация — перенос главной страницы в React

Первая стадия разбивки на компоненты — Sidebar и List (без разбивки стилей)
Подлкючены шрифты и картинки, включая svg

2017-05-11 10:50 UTC, imevro requested changes
Нужны правки (в основном цсс), но в целом ок

2017-05-11 10:50 UTC, evgenyrodionov commented on src/App.js
> +import Sidebar from './Sidebar/Sidebar';
`Sidebar/Sidebar.js` → `Sidebar/index.js`, тогда сможешь импортить как `from './Sidebar'`

2017-05-11 10:50 UTC, evgenyrodionov commented on src/List/List.js
> +import shoes from './shoes-1.jpg';
Лучше через require()

2017-05-11 10:50 UTC, evgenyrodionov commented on src/List/List.js
> +const IconFilter = React.createClass({
Без `createClass`

2017-05-11 10:50 UTC, evgenyrodionov commented on src/Sidebar/Sidebar.js
> +        <ul className="menu">
Откуда тут взялся список?

2017-05-11 10:50 UTC, evgenyrodionov commented on src/App.js
> +import Sidebar from './Sidebar/index';
Не, просто `./Sidebar`

2017-05-11 10:50 UTC, evgenyrodionov commented on src/List/Card/index.js
> +import shoes from './shoes-1.jpg';
Лучше через `require()`

2017-05-11 10:50 UTC, evgenyrodionov commented on src/List/Card/style.css
> +  -ms-flex-align: center;
В CRA есть автопрефиксер, поэтому нет нужды руками их прописывать

2017-05-12 08:34 UTC, prostofrost commented
@evgenyrodionov 

— Исправления по комментариями (убраны префиксы, картинки подключены через require, переверстан блок меню и пр.)

— Добавлены компоненты второй страницы, разбиты по смысловым элементам;
— Переиспользован Label sale.

Следующий этап: роутинг и стили.

2017-05-12 09:39 UTC, imevro approved these changes
Норм, но поправь эти мелочи

2017-05-12 09:39 UTC, evgenyrodionov commented on src/App.js
> +      <div className="flex-fixed">
Неочевидное название, не понимаю что оно значит

2017-05-12 09:39 UTC, evgenyrodionov commented on src/List/Filters/index.js
> +const IconFilter = () => ({
Объявление должна быть раньше вызова

2017-05-12 09:39 UTC, evgenyrodionov commented on src/flexboxgrid.css
> +.row {
Поставь из нпма, а ещё лучше реакт-флекбокс-грид

2017-05-12 09:39 UTC, evgenyrodionov commented on src/index.js
> +import './normalize.css';
Тоже из нпма можно

2017-05-12 16:21 UTC, prostofrost commented
@evgenyrodionov 

— Исправления по замечаниям;
— добавлен normalize.css из npm;
— добавлен react-flexbox-grid, переписана сетка.

2017-05-12 17:50 UTC, imevro approved these changes
Гуд

2017-05-12 17:50 UTC, evgenyrodionov commented on src/Sidebar/Logo/index.js
> +      <a href="#">
Линк из рроутера

2017-05-12 17:50 UTC, merged

2017-05-12 17:50 UTC, evgenyrodionov commented
Прикручивай стайлед-компонентс