Feat routing and styling
prostofrost/adidas-shop-react pull request #3
Opened 2017-05-12 18:33 UTC by prostofrost

— Устновлен и прописан роутинг.

Следующий этап styled-components

2017-05-12 18:45 UTC, imevro reviewed
Добей роутинг

2017-05-12 18:45 UTC, evgenyrodionov commented on src/List/Card/index.js
> +      <a href="/item" className="product-card-price">
Link из реакт-роутера

2017-05-12 18:45 UTC, evgenyrodionov commented on src/Sidebar/Logo/index.js
> +      <a href="/">
Тоже

2017-05-13 17:00 UTC, prostofrost commented
@evgenyrodionov 

— Исправлены недоработки по роутингу;
— Код отформатирован по линтеру;
— Большая часть стилей перенесена в компоненты, продолжаю перенос.

2017-05-13 18:44 UTC, imevro requested changes
Пофикси

2017-05-13 18:44 UTC, evgenyrodionov commented on .eslintrc
> +    "max-len": [
Возвращай обратно, нельзя менять конфиг

2017-05-13 18:44 UTC, evgenyrodionov commented on src/List/Card/index.jsx
> +  <Card className="product-card product-card-sale">
У тебя же sc?

2017-05-13 18:44 UTC, evgenyrodionov commented on src/List/Filters/index.jsx
> +  render() {
ээээ? Откуда рендер внутри функции взялся?

2017-05-13 18:44 UTC, evgenyrodionov commented on src/index.js
> +import '../node_modules/normalize.css/normalize.css';
import 'normalize.css'

2017-05-14 00:45 UTC, prostofrost commented
@evgenyrodionov

— Исправления по замечаниям;
— Завершен перенос стилей в styled components;
— деплой [](http://prostofrost.surge.sh/)

2017-05-14 09:46 UTC, imevro approved these changes
Норм

2017-05-14 09:47 UTC, merged